[package]
name = "native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1"
base64 = "0.21.0"
bincode = "1.3.3"
epub = "2.0.0"
flutter_rust_bridge = "1"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
serde = { version = "1.0.155", features = ["derive"] }
ureq = { version = "2.6.2", features = ["json"] }
uuid = { version = "1.3.0", features = ["v4", "fast-rng"] }
