[package]
name = "native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1"
epub = "2.0.0"
flutter_rust_bridge = "1"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
