#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.72.1.

use crate::books::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

use crate::types::Book;
use crate::types::ContentBlock;
use crate::types::ContentType;
use crate::types::GoUrlResult;
use crate::types::Meta;
use crate::types::OpenDocumentId;
use crate::types::Position;
use crate::types::TocEntry;

// Section: wire functions

fn wire_init_app_impl(port_: MessagePort, data_dir: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_data_dir = data_dir.wire2api();
            move |task_callback| init_app(api_data_dir)
        },
    )
}
fn wire_open_doc_impl(
    port_: MessagePort,
    path: impl Wire2Api<String> + UnwindSafe,
    initial_chapter: impl Wire2Api<Option<usize>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "open_doc",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_path = path.wire2api();
            let api_initial_chapter = initial_chapter.wire2api();
            move |task_callback| open_doc(api_path, api_initial_chapter)
        },
    )
}
fn wire_get_db_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_db",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| Ok(get_db()),
    )
}
fn wire_clear_db_impl(port_: MessagePort) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "clear_db",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || move |task_callback| clear_db(),
    )
}
fn wire_get_meta_impl(port_: MessagePort, id: impl Wire2Api<String> + UnwindSafe) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_meta",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_id = id.wire2api();
            move |task_callback| get_meta(api_id)
        },
    )
}
fn wire_go_next__method__OpenDocument_impl(
    port_: MessagePort,
    that: impl Wire2Api<OpenDocument> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "go_next__method__OpenDocument",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_that = that.wire2api();
            move |task_callback| OpenDocument::go_next(&api_that)
        },
    )
}
fn wire_go_prev__method__OpenDocument_impl(
    port_: MessagePort,
    that: impl Wire2Api<OpenDocument> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "go_prev__method__OpenDocument",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_that = that.wire2api();
            move |task_callback| OpenDocument::go_prev(&api_that)
        },
    )
}
fn wire_go_url__method__OpenDocument_impl(
    port_: MessagePort,
    that: impl Wire2Api<OpenDocument> + UnwindSafe,
    url: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "go_url__method__OpenDocument",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_that = that.wire2api();
            let api_url = url.wire2api();
            move |task_callback| OpenDocument::go_url(&api_that, api_url)
        },
    )
}
fn wire_get_content__method__OpenDocument_impl(
    port_: MessagePort,
    that: impl Wire2Api<OpenDocument> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_content__method__OpenDocument",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_that = that.wire2api();
            move |task_callback| OpenDocument::get_content(&api_that)
        },
    )
}
fn wire_get_resource__method__OpenDocument_impl(
    port_: MessagePort,
    that: impl Wire2Api<OpenDocument> + UnwindSafe,
    path: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_resource__method__OpenDocument",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_that = that.wire2api();
            let api_path = path.wire2api();
            move |task_callback| OpenDocument::get_resource(&api_that, api_path)
        },
    )
}
fn wire_get_toc__method__OpenDocument_impl(
    port_: MessagePort,
    that: impl Wire2Api<OpenDocument> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_toc__method__OpenDocument",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_that = that.wire2api();
            move |task_callback| OpenDocument::get_toc(&api_that)
        },
    )
}
fn wire_add_book__method__Database_impl(
    port_: MessagePort,
    that: impl Wire2Api<Database> + UnwindSafe,
    path: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "add_book__method__Database",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_that = that.wire2api();
            let api_path = path.wire2api();
            move |task_callback| Database::add_book(&api_that, api_path)
        },
    )
}
fn wire_update_progress__method__Database_impl(
    port_: MessagePort,
    that: impl Wire2Api<Database> + UnwindSafe,
    id: impl Wire2Api<String> + UnwindSafe,
    chapter: impl Wire2Api<usize> + UnwindSafe,
    offset: impl Wire2Api<f64> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "update_progress__method__Database",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_that = that.wire2api();
            let api_id = id.wire2api();
            let api_chapter = chapter.wire2api();
            let api_offset = offset.wire2api();
            move |task_callback| {
                Database::update_progress(&api_that, api_id, api_chapter, api_offset)
            }
        },
    )
}
fn wire_get_books__method__Database_impl(
    port_: MessagePort,
    that: impl Wire2Api<Database> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_books__method__Database",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_that = that.wire2api();
            move |task_callback| Database::get_books(&api_that)
        },
    )
}
fn wire_get_book__method__Database_impl(
    port_: MessagePort,
    that: impl Wire2Api<Database> + UnwindSafe,
    uuid: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "get_book__method__Database",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_that = that.wire2api();
            let api_uuid = uuid.wire2api();
            move |task_callback| Database::get_book(&api_that, api_uuid)
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<f64> for f64 {
    fn wire2api(self) -> f64 {
        self
    }
}

impl Wire2Api<u64> for u64 {
    fn wire2api(self) -> u64 {
        self
    }
}
impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

impl Wire2Api<usize> for usize {
    fn wire2api(self) -> usize {
        self
    }
}
// Section: impl IntoDart

impl support::IntoDart for Book {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.uuid.into_dart(),
            self.path.into_dart(),
            self.position.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Book {}

impl support::IntoDart for ContentBlock {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.content.into_dart(),
            self.chapter.into_dart(),
            self.content_type.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for ContentBlock {}

impl support::IntoDart for ContentType {
    fn into_dart(self) -> support::DartAbi {
        match self {
            Self::Html { extra_css } => vec![0.into_dart(), extra_css.into_dart()],
        }
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for ContentType {}
impl support::IntoDart for Database {
    fn into_dart(self) -> support::DartAbi {
        Vec::<u8>::new().into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Database {}

impl support::IntoDart for GoUrlResult {
    fn into_dart(self) -> support::DartAbi {
        vec![self.content.into_dart(), self.chapter.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for GoUrlResult {}

impl support::IntoDart for Meta {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.title.into_dart(),
            self.author.into_dart(),
            self.cover.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Meta {}

impl support::IntoDart for OpenDocument {
    fn into_dart(self) -> support::DartAbi {
        vec![self.id.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for OpenDocument {}

impl support::IntoDart for OpenDocumentId {
    fn into_dart(self) -> support::DartAbi {
        vec![self.0.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for OpenDocumentId {}

impl support::IntoDart for Position {
    fn into_dart(self) -> support::DartAbi {
        vec![self.chapter.into_dart(), self.offset.into_dart()].into_dart()
    }
}
impl support::IntoDartExceptPrimitive for Position {}

impl support::IntoDart for TocEntry {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.label.into_dart(),
            self.url.into_dart(),
            self.count.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for TocEntry {}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "books_generated.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
